project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    color: "pink"  # This sets the navbar color to pink.
    left:
      - text: "Hands-on Exercise"
        menu:  
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "Hands-on Exercise 5a"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05A.html"
          - text: "Hands-on Exercise 5b"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05B.html"
          - text: "Hands-on Exercise 5c"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05C.html"
          - text: "Hands-on Exercise 5d"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05D.html"
          - text: "Hands-on Exercise 5e"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05E.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 7a"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07A.html"
          - text: "Hands-on Exercise 7b"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07B.html"
          - text: "Hands-on Exercise 7c"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07C.html"
          - text: "Hands-on Exercise 8"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
          - text: "Hands-on Exercise 9"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
          - text: "Hands-on Exercise 10"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 6"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
          - text: "In-class Exercise 7"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
          - text: "In-class Exercise 8"
            href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
      - text: "Take-home Exercise"
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
          - text: "Take-home Exercise 4"
            href: "Take-home_Ex/Take-home_Ex04/Take-home_Ex04.html"
    center: 
      image: "pictures/background.jpg"  # Add your image in the center of the navbar.
    right:
      - href: index.qmd
        text: Home
      - about.qmd

output-dir: "_site"  # Directory where the website will be generated.

# Add the following to incorporate custom styling which is not natively supported by Quarto config.
# You would create a 'styles.css' with the necessary CSS to style the navbar and posts.
format:
  html:
    css: styles.css
    toc: true
    number-sections: false

editor: visual

# Add additional configurations to manage posts if Quarto supports it or handle it through custom scripts.
